language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
install:
  - composer install -o
  - composer require bamboohr/phpcs
script:
  - vendor/bin/phpunit tests
  - composer cs-check
  - php $TRAVIS_BUILD_DIR/src/bin/guardrail.php -i -s self.json
  - php $TRAVIS_BUILD_DIR/src/bin/guardrail.php -a -s self.json