language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer install -o
script:
  - cd tests;../vendor/bin/phpunit;cd ..
  - composer add-standard; composer cs-check;
  - php $TRAVIS_BUILD_DIR/src/bin/guardrail.php -i -s self.json
  - php $TRAVIS_BUILD_DIR/src/bin/guardrail.php -a -s self.json