language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
install: composer install -o
script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit tests/units
  - php $TRAVIS_BUILD_DIR/src/bin/guardrail.php -i -s self.json
  - php $TRAVIS_BUILD_DIR/src/bin/guardrail.php -a -s self.json