name: Continuous Integration
on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install -o

      - name: Unit Tests
        run: cd tests; ../vendor/bin/phpunit; cd ..

      - name: Static Index
        run: php src/bin/guardrail.php -i -s self.json

      - name: Static Analyze
        run: php src/bin/guardrail.php -a -s self.json
